config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'
  get 'restaurants', to: 'restaurants#index'

  get 'restaurants/new', to: 'restaurants#new'
  post "restaurants", to: 'restaurants#create'

  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  # reviews url:
  get "restaurants/:id/reviews", to: 'reviews#index', as: 'reviews'
  get 'restaurants/:id/reviews/new', to: 'reviews#new'
  post 'restaurants/:id/reviews', to: 'reviews#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen_string_literal: true

# Restaurant model
class Restaurant < ApplicationRecord
  # A restaurant has a 1 to n relationship with reviews
  # And when a restaurant gets deleted, the reviews associated should get deleted too
  has_many :reviews, dependent: :destroy
  # A restaurant must be created with name, address and category too
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  # A restaurant should only have categories from within this array
  CATEGORY = %w[chinese italian japanese french belgian].freeze
  validates :category, inclusion:
  { in: CATEGORY, message: 'Must belong to a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  # A review must have a parent restaurant
  belongs_to :restaurant, validate: true
  # A review must have content and rating when created
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  # A review must have a rating only between one to five
  RATINGS = [0, 1, 2, 3, 4, 5]
  validates :rating, inclusion: { in: RATINGS, message: 'Must be between 0 and 5' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
    @review = @restaurant.reviews.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant,
      notice: "Restaurant successfully created!"
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def index
    @reviews = @restaurant.reviews
  end

  def new
    @review = @restaurant.reviews.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      redirect_to restaurant_path,
      notice: 'Your review is logged!'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="container">
    <%= content_tag(:p, value, :class => "flash #{key}") %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id="wrapper">
      <% if flash[:notice] || flash[:alert] || flash[:danger] %>
        <%=render "layouts/flashes"  %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <p>test</p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h2>All restaurants</h2>
  <p><%= link_to("Add a new restaurant", restaurants_new_path)  %></p>
  <div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-md-4">
      <%= link_to(restaurant.name, restaurant ) %>
    </div>
  <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY, prompt: "Pick one" %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <h3>Address: <%= @restaurant.address %></h3>
  <h3>Phone Number: <%= @restaurant.phone_number %></h3>
  <h3>Category: <%= @restaurant.category %></h3>
</div>
<div class="container">
  <h2>Reviews for this restaurant:</h2>
  <% @reviews.each do |review| %>
    <%= review.content %>
  <% end %>
  <hr>
  <%= link_to("Add a new review", "/restaurants/#{params[:id]}/reviews/new" ) %>
  <%= simple_form_for @review do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::RATINGS, prompt: "Pick one" %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::RATINGS, prompt: "Pick one" %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <h2>New review</h2>
  <%= render 'form' %>
</div>